from unittest import TestCase
from pygds.amadeus.helpers import FormatSoapAmadeus


class TestFormatSoapAmadeus(TestCase):

    def setUp(self):
        self.xml_object = f"""
        <soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:awsse="http://xml.amadeus.com/2010/06/Session_v3" xmlns:wsa="http://www.w3.org/2005/08/addressing">
            <soapenv:Header>
                <wsa:To>http://www.w3.org/2005/08/addressing/anonymous</wsa:To>
                <wsa:From>
                    <wsa:Address>https://nodeD1.test.webservices.amadeus.com/1ASIWCTSCSO</wsa:Address>
                </wsa:From>
                <wsa:Action>http://webservices.amadeus.com/PNRRET_17_1_1A</wsa:Action>
                <wsa:MessageID>urn:uuid:22531eba-e326-0ca4-9559-fc0141c26672</wsa:MessageID>
                <wsa:RelatesTo RelationshipType="http://www.w3.org/2005/08/addressing/reply">WbsConsu-AmQ0ejr59Jb0SqVGIPyrMzIpNtmChxD-dMhZbcueZ</wsa:RelatesTo>
                <awsse:Session TransactionStatusCode="InSeries">
                    <awsse:SessionId>01N2KEFDNH</awsse:SessionId>
                    <awsse:SequenceNumber>1</awsse:SequenceNumber>
                    <awsse:SecurityToken>3JV85JJTBAWOM1RG9LXD8F5NUD</awsse:SecurityToken>
                </awsse:Session>
            </soapenv:Header>
            <soapenv:Body>
                <PNR_Reply xmlns="http://xml.amadeus.com/PNRACC_17_1_1A">
                    <pnrHeader>
                        <reservationInfo>
                        <reservation>
                            <companyId>1A</companyId>
                            <controlNumber>QK2W23</controlNumber>
                            <date>250619</date>
                            <time>1329</time>
                        </reservation>
                        </reservationInfo>
                    </pnrHeader>
                    <securityInformation>
                        <responsibilityInformation>
                        <typeOfPnrElement>RP</typeOfPnrElement>
                        <agentId>WSSU</agentId>
                        <officeId>DTW1S210B</officeId>
                        <iataCode>23612444</iataCode>
                        </responsibilityInformation>
                        <queueingInformation>
                        <queueingOfficeId>DTW1S210B</queueingOfficeId>
                        </queueingInformation>
                        <cityCode>DTW</cityCode>
                        <secondRpInformation>
                        <creationOfficeId>DTW1S210B</creationOfficeId>
                        <agentSignature>9995WS</agentSignature>
                        <creationDate>250619</creationDate>
                        <creatorIataCode>23612444</creatorIataCode>
                        <creationTime>1329</creationTime>
                        </secondRpInformation>
                    </securityInformation>
                    <freetextData>
                        <freetextDetail>
                        <subjectQualifier>3</subjectQualifier>
                        <type>P12</type>
                        </freetextDetail>
                        <longFreetext>--- TST RLR ---</longFreetext>
                    </freetextData>
                    <pnrHeaderTag>
                        <statusInformation>
                        <indicator>TST</indicator>
                        </statusInformation>
                        <statusInformation>
                        <indicator>RLR</indicator>
                        </statusInformation>
                    </pnrHeaderTag>
                    <sbrPOSDetails>
                        <sbrUserIdentificationOwn>
                        <originIdentification>
                            <originatorId>23612444</originatorId>
                            <inHouseIdentification1>DTW1S210B</inHouseIdentification1>
                        </originIdentification>
                        <originatorTypeCode>T</originatorTypeCode>
                        </sbrUserIdentificationOwn>
                        <sbrSystemDetails>
                        <deliveringSystem>
                            <companyId>1A</companyId>
                            <locationId>DTW</locationId>
                        </deliveringSystem>
                        </sbrSystemDetails>
                        <sbrPreferences>
                        <userPreferences>
                            <codedCountry>US</codedCountry>
                        </userPreferences>
                        </sbrPreferences>
                    </sbrPOSDetails>
                    <sbrCreationPosDetails>
                        <sbrUserIdentificationOwn>
                        <originIdentification>
                            <originatorId>23612444</originatorId>
                            <inHouseIdentification1>DTW1S210B</inHouseIdentification1>
                        </originIdentification>
                        <originatorTypeCode>T</originatorTypeCode>
                        </sbrUserIdentificationOwn>
                        <sbrSystemDetails>
                        <deliveringSystem>
                            <companyId>1A</companyId>
                            <locationId>DTW</locationId>
                        </deliveringSystem>
                        </sbrSystemDetails>
                        <sbrPreferences>
                        <userPreferences>
                            <codedCountry>US</codedCountry>
                        </userPreferences>
                        </sbrPreferences>
                    </sbrCreationPosDetails>
                    <sbrUpdatorPosDetails>
                        <sbrUserIdentificationOwn>
                        <originIdentification>
                            <originatorId>23612444</originatorId>
                            <inHouseIdentification1>DTW1S210B</inHouseIdentification1>
                        </originIdentification>
                        <originatorTypeCode>T</originatorTypeCode>
                        </sbrUserIdentificationOwn>
                        <sbrSystemDetails>
                        <deliveringSystem>
                            <companyId>1A</companyId>
                            <locationId>DTW</locationId>
                        </deliveringSystem>
                        </sbrSystemDetails>
                        <sbrPreferences>
                        <userPreferences>
                            <codedCountry>US</codedCountry>
                        </userPreferences>
                        </sbrPreferences>
                    </sbrUpdatorPosDetails>
                    <technicalData>
                        <enveloppeNumberData>
                        <sequenceDetails>
                            <number>1</number>
                        </sequenceDetails>
                        </enveloppeNumberData>
                        <lastTransmittedEnvelopeNumber>
                        <currentRecord>0</currentRecord>
                        </lastTransmittedEnvelopeNumber>
                        <purgeDateData>
                        <dateTime>
                            <year>2019</year>
                            <month>8</month>
                            <day>6</day>
                        </dateTime>
                        </purgeDateData>
                    </technicalData>
                    <travellerInfo>
                        <elementManagementPassenger>
                        <reference>
                            <qualifier>PT</qualifier>
                            <number>3</number>
                        </reference>
                        <segmentName>NM</segmentName>
                        <lineNumber>1</lineNumber>
                        </elementManagementPassenger>
                        <passengerData>
                        <travellerInformation>
                            <traveller>
                                <surname>ALEX</surname>
                                <quantity>1</quantity>
                            </traveller>
                            <passenger>
                                <firstName>ANDRA</firstName>
                                <type>ADT</type>
                            </passenger>
                        </travellerInformation>
                        <dateOfBirth>
                            <dateAndTimeDetails>
                                <qualifier>706</qualifier>
                                <date>01011960</date>
                            </dateAndTimeDetails>
                        </dateOfBirth>
                        </passengerData>
                        <enhancedPassengerData>
                        <enhancedTravellerInformation>
                            <travellerNameInfo>
                                <quantity>1</quantity>
                                <type>ADT</type>
                            </travellerNameInfo>
                            <otherPaxNamesDetails>
                                <nameType>UN</nameType>
                                <referenceName>Y</referenceName>
                                <displayedName>Y</displayedName>
                                <surname>ALEX</surname>
                                <givenName>ANDRA</givenName>
                            </otherPaxNamesDetails>
                        </enhancedTravellerInformation>
                        <dateOfBirthInEnhancedPaxData>
                            <dateAndTimeDetails>
                                <qualifier>706</qualifier>
                                <date>01011960</date>
                            </dateAndTimeDetails>
                        </dateOfBirthInEnhancedPaxData>
                        </enhancedPassengerData>
                    </travellerInfo>
                    <travellerInfo>
                        <elementManagementPassenger>
                        <reference>
                            <qualifier>PT</qualifier>
                            <number>2</number>
                        </reference>
                        <segmentName>NM</segmentName>
                        <lineNumber>2</lineNumber>
                        </elementManagementPassenger>
                        <passengerData>
                        <travellerInformation>
                            <traveller>
                                <surname>BOLANOS</surname>
                                <quantity>1</quantity>
                            </traveller>
                            <passenger>
                                <firstName>GERMAIN</firstName>
                                <type>ADT</type>
                            </passenger>
                        </travellerInformation>
                        <dateOfBirth>
                            <dateAndTimeDetails>
                                <qualifier>706</qualifier>
                                <date>10061978</date>
                            </dateAndTimeDetails>
                        </dateOfBirth>
                        </passengerData>
                        <enhancedPassengerData>
                        <enhancedTravellerInformation>
                            <travellerNameInfo>
                                <quantity>1</quantity>
                                <type>ADT</type>
                            </travellerNameInfo>
                            <otherPaxNamesDetails>
                                <nameType>UN</nameType>
                                <referenceName>Y</referenceName>
                                <displayedName>Y</displayedName>
                                <surname>BOLANOS</surname>
                                <givenName>GERMAIN</givenName>
                            </otherPaxNamesDetails>
                        </enhancedTravellerInformation>
                        <dateOfBirthInEnhancedPaxData>
                            <dateAndTimeDetails>
                                <qualifier>706</qualifier>
                                <date>10061978</date>
                            </dateAndTimeDetails>
                        </dateOfBirthInEnhancedPaxData>
                        </enhancedPassengerData>
                    </travellerInfo>
                    <originDestinationDetails>
                        <originDestination/>
                        <itineraryInfo>
                        <elementManagementItinerary>
                            <reference>
                                <qualifier>ST</qualifier>
                                <number>1</number>
                            </reference>
                            <segmentName>AIR</segmentName>
                            <lineNumber>3</lineNumber>
                        </elementManagementItinerary>
                        <travelProduct>
                            <product>
                                <depDate>300719</depDate>
                                <depTime>1045</depTime>
                                <arrDate>300719</arrDate>
                                <arrTime>1305</arrTime>
                            </product>
                            <boardpointDetail>
                                <cityCode>CDG</cityCode>
                            </boardpointDetail>
                            <offpointDetail>
                                <cityCode>WAW</cityCode>
                            </offpointDetail>
                            <companyDetail>
                                <identification>LO</identification>
                            </companyDetail>
                            <productDetails>
                                <identification>332</identification>
                                <classOfService>O</classOfService>
                            </productDetails>
                            <typeDetail>
                                <detail>ET</detail>
                            </typeDetail>
                        </travelProduct>
                        <itineraryMessageAction>
                            <business>
                                <function>1</function>
                            </business>
                        </itineraryMessageAction>
                        <itineraryReservationInfo>
                            <reservation>
                                <companyId>LO</companyId>
                                <controlNumber>QK2W23</controlNumber>
                            </reservation>
                        </itineraryReservationInfo>
                        <relatedProduct>
                            <quantity>2</quantity>
                            <status>HK</status>
                        </relatedProduct>
                        <flightDetail>
                            <productDetails>
                                <equipment>738</equipment>
                                <numOfStops>0</numOfStops>
                                <weekDay>2</weekDay>
                            </productDetails>
                            <departureInformation>
                                <departTerminal>1</departTerminal>
                            </departureInformation>
                            <facilities>
                                <entertainement>M</entertainement>
                                <entertainementDescription>RF</entertainementDescription>
                            </facilities>
                        </flightDetail>
                        <selectionDetails>
                            <selection>
                                <option>P2</option>
                            </selection>
                        </selectionDetails>
                        <carbonDioxydeInfo>
                            <carbonDioxydeAmount>
                                <quantityDetails>
                                    <qualifier>COE</qualifier>
                                    <value>143.808520</value>
                                    <unit>KPP</unit>
                                </quantityDetails>
                            </carbonDioxydeAmount>
                            <carbonDioxydeInfoSource>
                                <freeTextDetails>
                                    <textSubjectQualifier>3</textSubjectQualifier>
                                    <source>S</source>
                                    <encoding>7</encoding>
                                </freeTextDetails>
                                <freeText>SOURCE:ICAO CARBON EMISSIONS CALCULATOR</freeText>
                            </carbonDioxydeInfoSource>
                        </carbonDioxydeInfo>
                        <distributionMethod>
                            <methodCode>E</methodCode>
                        </distributionMethod>
                        <markerRailTour/>
                        </itineraryInfo>
                        <itineraryInfo>
                        <elementManagementItinerary>
                            <reference>
                                <qualifier>ST</qualifier>
                                <number>2</number>
                            </reference>
                            <segmentName>AIR</segmentName>
                            <lineNumber>4</lineNumber>
                        </elementManagementItinerary>
                        <travelProduct>
                            <product>
                                <depDate>020819</depDate>
                                <depTime>2015</depTime>
                                <arrDate>020819</arrDate>
                                <arrTime>2245</arrTime>
                            </product>
                            <boardpointDetail>
                                <cityCode>WAW</cityCode>
                            </boardpointDetail>
                            <offpointDetail>
                                <cityCode>CDG</cityCode>
                            </offpointDetail>
                            <companyDetail>
                                <identification>LO</identification>
                            </companyDetail>
                            <productDetails>
                                <identification>333</identification>
                                <classOfService>O</classOfService>
                            </productDetails>
                            <typeDetail>
                                <detail>ET</detail>
                            </typeDetail>
                        </travelProduct>
                        <itineraryMessageAction>
                            <business>
                                <function>1</function>
                            </business>
                        </itineraryMessageAction>
                        <itineraryReservationInfo>
                            <reservation>
                                <companyId>LO</companyId>
                                <controlNumber>QK2W23</controlNumber>
                            </reservation>
                        </itineraryReservationInfo>
                        <relatedProduct>
                            <quantity>2</quantity>
                            <status>HK</status>
                        </relatedProduct>
                        <flightDetail>
                            <productDetails>
                                <equipment>E95</equipment>
                                <numOfStops>0</numOfStops>
                                <weekDay>5</weekDay>
                            </productDetails>
                            <arrivalStationInfo>
                                <terminal>1</terminal>
                            </arrivalStationInfo>
                            <facilities>
                                <entertainement>M</entertainement>
                                <entertainementDescription>RF</entertainementDescription>
                            </facilities>
                        </flightDetail>
                        <selectionDetails>
                            <selection>
                                <option>P2</option>
                            </selection>
                        </selectionDetails>
                        <carbonDioxydeInfo>
                            <carbonDioxydeAmount>
                                <quantityDetails>
                                    <qualifier>COE</qualifier>
                                    <value>143.784909</value>
                                    <unit>KPP</unit>
                                </quantityDetails>
                            </carbonDioxydeAmount>
                            <carbonDioxydeInfoSource>
                                <freeTextDetails>
                                    <textSubjectQualifier>3</textSubjectQualifier>
                                    <source>S</source>
                                    <encoding>7</encoding>
                                </freeTextDetails>
                                <freeText>SOURCE:ICAO CARBON EMISSIONS CALCULATOR</freeText>
                            </carbonDioxydeInfoSource>
                        </carbonDioxydeInfo>
                        <distributionMethod>
                            <methodCode>E</methodCode>
                        </distributionMethod>
                        <markerRailTour/>
                        </itineraryInfo>
                    </originDestinationDetails>
                    <dataElementsMaster>
                        <marker2/>
                        <dataElementsIndiv>
                        <elementManagementData>
                            <reference>
                                <qualifier>OT</qualifier>
                                <number>5</number>
                            </reference>
                            <segmentName>AP</segmentName>
                            <lineNumber>5</lineNumber>
                        </elementManagementData>
                        <otherDataFreetext>
                            <freetextDetail>
                                <subjectQualifier>3</subjectQualifier>
                                <type>6</type>
                            </freetextDetail>
                            <longFreetext>0722541415</longFreetext>
                        </otherDataFreetext>
                        </dataElementsIndiv>
                        <dataElementsIndiv>
                        <elementManagementData>
                            <reference>
                                <qualifier>OT</qualifier>
                                <number>7</number>
                            </reference>
                            <segmentName>AP</segmentName>
                            <lineNumber>6</lineNumber>
                        </elementManagementData>
                        <otherDataFreetext>
                            <freetextDetail>
                                <subjectQualifier>3</subjectQualifier>
                                <type>P02</type>
                            </freetextDetail>
                            <longFreetext>GERMAIN.BOLANOS@AMADEUS.COM</longFreetext>
                        </otherDataFreetext>
                        </dataElementsIndiv>
                        <dataElementsIndiv>
                        <elementManagementData>
                            <reference>
                                <qualifier>OT</qualifier>
                                <number>6</number>
                            </reference>
                            <segmentName>AP</segmentName>
                            <lineNumber>7</lineNumber>
                        </elementManagementData>
                        <otherDataFreetext>
                            <freetextDetail>
                                <subjectQualifier>3</subjectQualifier>
                                <type>7</type>
                            </freetextDetail>
                            <longFreetext>0722541415</longFreetext>
                        </otherDataFreetext>
                        </dataElementsIndiv>
                        <dataElementsIndiv>
                        <elementManagementData>
                            <reference>
                                <qualifier>OT</qualifier>
                                <number>10</number>
                            </reference>
                            <segmentName>TK</segmentName>
                            <lineNumber>8</lineNumber>
                        </elementManagementData>
                        <ticketElement>
                            <ticket>
                                <indicator>OK</indicator>
                                <date>250619</date>
                                <officeId>DTW1S210B</officeId>
                            </ticket>
                        </ticketElement>
                        </dataElementsIndiv>
                        <dataElementsIndiv>
                        <elementManagementData>
                            <reference>
                                <qualifier>OT</qualifier>
                                <number>9</number>
                            </reference>
                            <segmentName>OP</segmentName>
                            <lineNumber>9</lineNumber>
                        </elementManagementData>
                        <otherDataFreetext>
                            <freetextDetail>
                                <subjectQualifier>3</subjectQualifier>
                                <type>P21</type>
                            </freetextDetail>
                            <longFreetext>DTW1S210B/25JUN</longFreetext>
                        </otherDataFreetext>
                        </dataElementsIndiv>
                        <dataElementsIndiv>
                        <elementManagementData>
                            <reference>
                                <qualifier>OT</qualifier>
                                <number>13</number>
                            </reference>
                            <segmentName>FE</segmentName>
                            <lineNumber>10</lineNumber>
                        </elementManagementData>
                        <otherDataFreetext>
                            <freetextDetail>
                                <subjectQualifier>3</subjectQualifier>
                                <type>10</type>
                            </freetextDetail>
                            <longFreetext>PAX NONREF/ NO CHNG</longFreetext>
                        </otherDataFreetext>
                        <referenceForDataElement>
                            <reference>
                                <qualifier>ST</qualifier>
                                <number>1</number>
                            </reference>
                            <reference>
                                <qualifier>ST</qualifier>
                                <number>2</number>
                            </reference>
                            <reference>
                                <qualifier>PT</qualifier>
                                <number>2</number>
                            </reference>
                            <reference>
                                <qualifier>PT</qualifier>
                                <number>3</number>
                            </reference>
                        </referenceForDataElement>
                        </dataElementsIndiv>
                        <dataElementsIndiv>
                        <elementManagementData>
                            <reference>
                                <qualifier>OT</qualifier>
                                <number>8</number>
                            </reference>
                            <segmentName>FM</segmentName>
                            <lineNumber>11</lineNumber>
                        </elementManagementData>
                        <otherDataFreetext>
                            <freetextDetail>
                                <subjectQualifier>3</subjectQualifier>
                                <type>11</type>
                            </freetextDetail>
                            <longFreetext>*M*5</longFreetext>
                        </otherDataFreetext>
                        </dataElementsIndiv>
                        <dataElementsIndiv>
                        <elementManagementData>
                            <reference>
                                <qualifier>OT</qualifier>
                                <number>11</number>
                            </reference>
                            <segmentName>FP</segmentName>
                            <lineNumber>12</lineNumber>
                        </elementManagementData>
                        <otherDataFreetext>
                            <freetextDetail>
                                <subjectQualifier>3</subjectQualifier>
                                <type>16</type>
                            </freetextDetail>
                            <longFreetext>CCVIXXXXXXXXXXXX4305/1020*CV</longFreetext>
                        </otherDataFreetext>
                        </dataElementsIndiv>
                        <dataElementsIndiv>
                        <elementManagementData>
                            <reference>
                                <qualifier>OT</qualifier>
                                <number>14</number>
                            </reference>
                            <segmentName>FV</segmentName>
                            <lineNumber>13</lineNumber>
                        </elementManagementData>
                        <otherDataFreetext>
                            <freetextDetail>
                                <subjectQualifier>3</subjectQualifier>
                                <type>P18</type>
                            </freetextDetail>
                            <longFreetext>PAX LO</longFreetext>
                        </otherDataFreetext>
                        <referenceForDataElement>
                            <reference>
                                <qualifier>ST</qualifier>
                                <number>1</number>
                            </reference>
                            <reference>
                                <qualifier>ST</qualifier>
                                <number>2</number>
                            </reference>
                            <reference>
                                <qualifier>PT</qualifier>
                                <number>2</number>
                            </reference>
                            <reference>
                                <qualifier>PT</qualifier>
                                <number>3</number>
                            </reference>
                        </referenceForDataElement>
                        </dataElementsIndiv>
                    </dataElementsMaster>
                    <tstData>
                        <tstGeneralInformation>
                        <generalInformation>
                            <tstReferenceNumber>1</tstReferenceNumber>
                            <tstCreationDate>250619</tstCreationDate>
                        </generalInformation>
                        </tstGeneralInformation>
                        <tstFreetext>
                        <freetextDetail>
                            <subjectQualifier>3</subjectQualifier>
                            <type>41</type>
                        </freetextDetail>
                        <longFreetext>PAX</longFreetext>
                        </tstFreetext>
                        <tstFreetext>
                        <freetextDetail>
                            <subjectQualifier>3</subjectQualifier>
                            <type>37</type>
                        </freetextDetail>
                        <longFreetext>PAR LO WAW11.75OSAVJ7 LO PAR11.75OSAVJ7 NUC23.50END ROE0.893096</longFreetext>
                        </tstFreetext>
                        <fareBasisInfo>
                        <fareElement>
                            <primaryCode>OSA</primaryCode>
                            <notValidBefore>300719</notValidBefore>
                            <notValidAfter>300719</notValidAfter>
                            <baggageAllowance>0PC</baggageAllowance>
                            <fareBasis>VJ7</fareBasis>
                        </fareElement>
                        <fareElement>
                            <primaryCode>OSA</primaryCode>
                            <connection>O</connection>
                            <notValidBefore>020819</notValidBefore>
                            <notValidAfter>020819</notValidAfter>
                            <baggageAllowance>0PC</baggageAllowance>
                            <fareBasis>VJ7</fareBasis>
                        </fareElement>
                        </fareBasisInfo>
                        <fareData>
                        <issueIdentifier>F</issueIdentifier>
                        <monetaryInfo>
                            <qualifier>F</qualifier>
                            <amount>21.00</amount>
                            <currencyCode>EUR</currencyCode>
                        </monetaryInfo>
                        <monetaryInfo>
                            <qualifier>E</qualifier>
                            <amount>24.00</amount>
                            <currencyCode>USD</currencyCode>
                        </monetaryInfo>
                        <monetaryInfo>
                            <qualifier>T</qualifier>
                            <amount>107.12</amount>
                            <currencyCode>USD</currencyCode>
                        </monetaryInfo>
                        <taxFields>
                            <taxIndicator>X</taxIndicator>
                            <taxCurrency>USD</taxCurrency>
                            <taxAmount>33.86</taxAmount>
                            <taxCountryCode>YQ</taxCountryCode>
                            <taxNatureCode>AC</taxNatureCode>
                        </taxFields>
                        <taxFields>
                            <taxIndicator>X</taxIndicator>
                            <taxCurrency>USD</taxCurrency>
                            <taxAmount>13.48</taxAmount>
                            <taxCountryCode>QX</taxCountryCode>
                            <taxNatureCode>AP</taxNatureCode>
                        </taxFields>
                        <taxFields>
                            <taxIndicator>X</taxIndicator>
                            <taxCurrency>USD</taxCurrency>
                            <taxAmount>1.28</taxAmount>
                            <taxCountryCode>IZ</taxCountryCode>
                            <taxNatureCode>EB</taxNatureCode>
                        </taxFields>
                        <taxFields>
                            <taxIndicator>X</taxIndicator>
                            <taxCurrency>USD</taxCurrency>
                            <taxAmount>5.17</taxAmount>
                            <taxCountryCode>FR</taxCountryCode>
                            <taxNatureCode>SE</taxNatureCode>
                        </taxFields>
                        <taxFields>
                            <taxIndicator>X</taxIndicator>
                            <taxCurrency>USD</taxCurrency>
                            <taxAmount>13.21</taxAmount>
                            <taxCountryCode>FR</taxCountryCode>
                            <taxNatureCode>TI</taxNatureCode>
                        </taxFields>
                        <taxFields>
                            <taxIndicator>X</taxIndicator>
                            <taxCurrency>USD</taxCurrency>
                            <taxAmount>0.21</taxAmount>
                            <taxCountryCode>ND</taxCountryCode>
                            <taxNatureCode>AD</taxNatureCode>
                        </taxFields>
                        <taxFields>
                            <taxIndicator>X</taxIndicator>
                            <taxCurrency>USD</taxCurrency>
                            <taxAmount>15.91</taxAmount>
                            <taxCountryCode>XW</taxCountryCode>
                            <taxNatureCode>AE</taxNatureCode>
                        </taxFields>
                        </fareData>
                        <segmentAssociation>
                        <selection>
                            <option>N</option>
                        </selection>
                        <selection>
                            <option>I</option>
                        </selection>
                        </segmentAssociation>
                        <referenceForTstData>
                        <reference>
                            <qualifier>PT</qualifier>
                            <number>2</number>
                        </reference>
                        <reference>
                            <qualifier>PT</qualifier>
                            <number>3</number>
                        </reference>
                        <reference>
                            <qualifier>ST</qualifier>
                            <number>1</number>
                        </reference>
                        <reference>
                            <qualifier>ST</qualifier>
                            <number>2</number>
                        </reference>
                        </referenceForTstData>
                    </tstData>
                    <pricingRecordGroup>
                        <pricingRecordData/>
                        <productPricingQuotationRecord>
                        <pricingRecordId>
                            <referenceType>TST</referenceType>
                            <uniqueReference>1</uniqueReference>
                        </pricingRecordId>
                        <passengerTattoos>
                            <passengerReference>
                                <type>PA</type>
                                <value>2</value>
                            </passengerReference>
                        </passengerTattoos>
                        <passengerTattoos>
                            <passengerReference>
                                <type>PA</type>
                                <value>3</value>
                            </passengerReference>
                        </passengerTattoos>
                        <documentDetailsGroup>
                            <totalFare>
                                <monetaryDetails>
                                    <typeQualifier>T</typeQualifier>
                                    <amount>107.12</amount>
                                    <currency>USD</currency>
                                </monetaryDetails>
                            </totalFare>
                            <issueIdentifier>
                                <priceTicketDetails>
                                    <indicators>I</indicators>
                                </priceTicketDetails>
                                <priceTariffType>F</priceTariffType>
                            </issueIdentifier>
                            <manualIndicator>
                                <statusDetails>
                                    <indicator>M</indicator>
                                    <action>N</action>
                                </statusDetails>
                            </manualIndicator>
                            <officeInformation>
                                <originIdentification>
                                    <inHouseIdentification1>DTW1S210B</inHouseIdentification1>
                                    <inHouseIdentification2>WS</inHouseIdentification2>
                                </originIdentification>
                            </officeInformation>
                            <creationDate>
                                <businessSemantic>CRD</businessSemantic>
                                <dateTime>
                                    <year>2019</year>
                                    <month>06</month>
                                    <day>25</day>
                                </dateTime>
                            </creationDate>
                            <couponDetailsGroup>
                                <productId>
                                    <referenceDetails>
                                    <type>ST</type>
                                    <value>1</value>
                                    </referenceDetails>
                                </productId>
                            </couponDetailsGroup>
                            <couponDetailsGroup>
                                <productId>
                                    <referenceDetails>
                                    <type>ST</type>
                                    <value>2</value>
                                    </referenceDetails>
                                </productId>
                            </couponDetailsGroup>
                            <fareComponentDetailsGroup>
                                <fareComponentID>
                                    <itemNumberDetails>
                                    <number>1</number>
                                    <type>FAR</type>
                                    </itemNumberDetails>
                                </fareComponentID>
                                <marketFareComponent>
                                    <boardPointDetails>
                                    <trueLocationId>PAR</trueLocationId>
                                    </boardPointDetails>
                                    <offpointDetails>
                                    <trueLocationId>WAW</trueLocationId>
                                    </offpointDetails>
                                </marketFareComponent>
                                <monetaryInformation>
                                    <monetaryDetails>
                                    <typeQualifier>B</typeQualifier>
                                    <amount>11.75</amount>
                                    <currency>NUC</currency>
                                    </monetaryDetails>
                                </monetaryInformation>
                                <componentClassInfo>
                                    <fareBasisDetails>
                                    <rateTariffClass>OSAVJ7</rateTariffClass>
                                    </fareBasisDetails>
                                </componentClassInfo>
                                <fareQualifiersDetail>
                                    <discountDetails>
                                    <fareQualifier>763</fareQualifier>
                                    </discountDetails>
                                </fareQualifiersDetail>
                                <fareFamilyDetails>
                                    <fareFamilyname>ECOSAVER</fareFamilyname>
                                </fareFamilyDetails>
                                <fareFamilyOwner>
                                    <companyIdentification>
                                    <otherCompany>LO</otherCompany>
                                    </companyIdentification>
                                </fareFamilyOwner>
                                <couponDetailsGroup>
                                    <productId>
                                    <referenceDetails>
                                        <type>ST</type>
                                        <value>1</value>
                                    </referenceDetails>
                                    </productId>
                                </couponDetailsGroup>
                            </fareComponentDetailsGroup>
                            <fareComponentDetailsGroup>
                                <fareComponentID>
                                    <itemNumberDetails>
                                    <number>2</number>
                                    <type>FAR</type>
                                    </itemNumberDetails>
                                </fareComponentID>
                                <marketFareComponent>
                                    <boardPointDetails>
                                    <trueLocationId>WAW</trueLocationId>
                                    </boardPointDetails>
                                    <offpointDetails>
                                    <trueLocationId>PAR</trueLocationId>
                                    </offpointDetails>
                                </marketFareComponent>
                                <monetaryInformation>
                                    <monetaryDetails>
                                    <typeQualifier>B</typeQualifier>
                                    <amount>11.75</amount>
                                    <currency>NUC</currency>
                                    </monetaryDetails>
                                </monetaryInformation>
                                <componentClassInfo>
                                    <fareBasisDetails>
                                    <rateTariffClass>OSAVJ7</rateTariffClass>
                                    </fareBasisDetails>
                                </componentClassInfo>
                                <fareQualifiersDetail>
                                    <discountDetails>
                                    <fareQualifier>763</fareQualifier>
                                    </discountDetails>
                                </fareQualifiersDetail>
                                <fareFamilyDetails>
                                    <fareFamilyname>ECOSAVER</fareFamilyname>
                                </fareFamilyDetails>
                                <fareFamilyOwner>
                                    <companyIdentification>
                                    <otherCompany>LO</otherCompany>
                                    </companyIdentification>
                                </fareFamilyOwner>
                                <couponDetailsGroup>
                                    <productId>
                                    <referenceDetails>
                                        <type>ST</type>
                                        <value>2</value>
                                    </referenceDetails>
                                    </productId>
                                </couponDetailsGroup>
                            </fareComponentDetailsGroup>
                        </documentDetailsGroup>
                        </productPricingQuotationRecord>
                    </pricingRecordGroup>
                </PNR_Reply>
            </soapenv:Body>
        </soapenv:Envelope>
        """
        self.json_object = FormatSoapAmadeus().soap_service_to_json(self.xml_object)

    def test_soap_service_to_json(self):
        result = FormatSoapAmadeus().soap_service_to_json(self.xml_object)
        self.assertTrue(isinstance(result, object))
        self.assertIsNotNone(result)

    def test_get_segments(self):
        result = FormatSoapAmadeus().get_segments(self.json_object)
        self.assertIsNotNone(result)

    def test_get_passengers(self):
        result = FormatSoapAmadeus().get_passengers(self.json_object)
        self.assertIsNotNone(result)

    # def test_get_pnr_infos(self):
    #     result = FormatSoapAmadeus().get_pnr_infos(self.json_object)
    #     self.assertIsNotNone(result)

    # def test_get_form_of_payments(self):
    #     result = FormatSoapAmadeus().get_form_of_payments(self.json_object)
    #     self.assertIsNotNone(result)

    # def test_get_price_quotes(self):
    #     result = FormatSoapAmadeus().get_price_quotes(self.json_object)
    #     self.assertIsNotNone(result)

    # def test_get_ticketing_info(self):
    #     result = FormatSoapAmadeus().get_ticketing_info(self.json_object)
    #     self.assertIsNotNone(result)

    # def test_get_reservation_response(self):
    #     result = FormatSoapAmadeus().get_reservation_response(self.json_object)
    #     self.assertIsNotNone(result)
